/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *afficher_elections;
  GtkWidget *gestion_elections;
  GtkWidget *espace_admin;
  GtkWidget *ajouter_bv;
  GtkWidget *afficher_bv;
  GtkWidget *gestion_utilisateur;
  GtkWidget *afficher_utilisateur;
  GtkWidget *statbv1;
  
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  afficher_elections = create_afficher_elections ();
  gtk_widget_show (afficher_elections);
  gestion_elections = create_gestion_elections ();
  gtk_widget_show (gestion_elections);
  espace_admin = create_espace_admin ();
  gtk_widget_show (espace_admin);
  ajouter_bv = create_ajouter_bv ();
  gtk_widget_show (ajouter_bv);
  afficher_bv = create_afficher_bv ();
  gtk_widget_show (afficher_bv);
  gestion_utilisateur = create_gestion_utilisateur ();
  gtk_widget_show (gestion_utilisateur);
  afficher_utilisateur = create_afficher_utilisateur ();
  gtk_widget_show (afficher_utilisateur);
  statbv1 =create_statbv1();
  gtk_widget_show (statbv1);
  

  gtk_main ();
  return 0;
}

